-- 领星 /erp/sc/data/mws_report/fbaOrders 原始 FBA 订单地址事实。
-- 生产探针确认城市、州、邮编、国家可用；本表不保存街道、姓名、电话、邮箱等个人字段。
-- sid 来自请求参数回填，响应本身不返回 sid。
CREATE TABLE IF NOT EXISTS ls_sc_fba_order_addresses (
    account_id                 VARCHAR(32)  NOT NULL COMMENT '本系统内部账号 ID',
    sid                        VARCHAR(32)  NOT NULL COMMENT '请求店铺 ID',
    amazon_order_id            VARCHAR(64)  NOT NULL,
    shipment_id                VARCHAR(64)  NOT NULL,
    shipment_item_id           VARCHAR(64)  NOT NULL,
    amazon_order_item_id       VARCHAR(64)  NULL,
    purchase_date              VARCHAR(40)  NULL,
    payments_date              VARCHAR(40)  NULL,
    shipment_date              VARCHAR(40)  NULL,
    reporting_date             VARCHAR(40)  NULL,
    estimated_arrival_date     VARCHAR(40)  NULL,
    sku                        VARCHAR(256) NULL,
    product_name               VARCHAR(512) NULL,
    quantity_shipped           INT          NULL,
    currency                   VARCHAR(8)   NULL,
    item_price                 VARCHAR(32)  NULL,
    item_tax                   VARCHAR(32)  NULL,
    shipping_price             VARCHAR(32)  NULL,
    shipping_tax               VARCHAR(32)  NULL,
    gift_wrap_price            VARCHAR(32)  NULL,
    gift_wrap_tax              VARCHAR(32)  NULL,
    ship_service_level         VARCHAR(64)  NULL,
    item_promotion_discount    VARCHAR(32)  NULL,
    ship_promotion_discount    VARCHAR(32)  NULL,
    carrier                    VARCHAR(64)  NULL,
    tracking_number            VARCHAR(128) NULL,
    fulfillment_channel        VARCHAR(32)  NULL,
    points_granted             VARCHAR(32)  NULL,
    hide_time                  VARCHAR(40)  NULL,
    ship_city                  VARCHAR(128) NULL,
    ship_state                 VARCHAR(128) NULL,
    ship_postal_code           VARCHAR(32)  NULL,
    ship_country               VARCHAR(8)   NULL,
    synced_at                  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (account_id, sid, shipment_id, shipment_item_id),
    INDEX idx_order (account_id, sid, amazon_order_id),
    INDEX idx_purchase_date (account_id, sid, purchase_date),
    INDEX idx_postal (account_id, ship_country, ship_postal_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '领星 SC FBA 订单地址原始事实（地理字段）';
