-- Formal Amazon archived FBA inventory report evidence. The archived report
-- has the same official 21 source columns as MYI, but retains its own rows.
CREATE TABLE IF NOT EXISTS ls_fba_myi_all_inventory (
    account_id                         VARCHAR(32)  NOT NULL,
    seller_id                          VARCHAR(64)  NOT NULL,
    store_id                           VARCHAR(64)  NOT NULL DEFAULT '',
    report_task_id                     VARCHAR(128) NOT NULL,
    `row_number`                       INT UNSIGNED NOT NULL,
    row_sha256                         CHAR(64)     NOT NULL,
    sku                                VARCHAR(256) NULL,
    fnsku                              VARCHAR(64)  NULL,
    asin                               VARCHAR(32)  NULL,
    `product-name`                     TEXT         NULL,
    `condition`                        VARCHAR(64)  NULL,
    `your-price`                       VARCHAR(64)  NULL,
    `mfn-listing-exists`               VARCHAR(32)  NULL,
    `mfn-fulfillable-quantity`         VARCHAR(32)  NULL,
    `afn-listing-exists`               VARCHAR(32)  NULL,
    `afn-warehouse-quantity`           VARCHAR(32)  NULL,
    `afn-fulfillable-quantity`         VARCHAR(32)  NULL,
    `afn-unsellable-quantity`          VARCHAR(32)  NULL,
    `afn-reserved-quantity`            VARCHAR(32)  NULL,
    `afn-total-quantity`               VARCHAR(32)  NULL,
    `per-unit-volume`                  VARCHAR(64)  NULL,
    `afn-inbound-working-quantity`     VARCHAR(32)  NULL,
    `afn-inbound-shipped-quantity`     VARCHAR(32)  NULL,
    `afn-inbound-receiving-quantity`   VARCHAR(32)  NULL,
    `afn-researching-quantity`         VARCHAR(32)  NULL,
    `afn-reserved-future-supply`       VARCHAR(32)  NULL,
    `afn-future-supply-buyable`        VARCHAR(32)  NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_myi_all_inventory_scope (account_id, seller_id, store_id),
    INDEX idx_fba_myi_all_inventory_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA MYI archived inventory formal report raw rows';
