-- Formal Amazon FBA reimbursements report evidence.
CREATE TABLE IF NOT EXISTS ls_fba_reimbursements (
    account_id                       VARCHAR(32)  NOT NULL,
    seller_id                        VARCHAR(64)  NOT NULL,
    store_id                         VARCHAR(64)  NOT NULL DEFAULT '',
    report_task_id                   VARCHAR(128) NOT NULL,
    `row_number`                     INT UNSIGNED NOT NULL,
    row_sha256                       CHAR(64)     NOT NULL,
    `approval-date`                  VARCHAR(40)  NULL,
    `reimbursement-id`               VARCHAR(128) NULL,
    `case-id`                        VARCHAR(128) NULL,
    `amazon-order-id`                VARCHAR(128) NULL,
    reason                           VARCHAR(256) NULL,
    sku                              VARCHAR(256) NULL,
    fnsku                            VARCHAR(64)  NULL,
    asin                             VARCHAR(32)  NULL,
    `product-name`                   TEXT         NULL,
    `condition`                      VARCHAR(64)  NULL,
    `currency-unit`                  VARCHAR(16)  NULL,
    `amount-per-unit`                VARCHAR(64)  NULL,
    `amount-total`                   VARCHAR(64)  NULL,
    `quantity-reimbursed-cash`       VARCHAR(32)  NULL,
    `quantity-reimbursed-inventory`  VARCHAR(32)  NULL,
    `quantity-reimbursed-total`      VARCHAR(32)  NULL,
    `original-reimbursement-id`      VARCHAR(128) NULL,
    `original-reimbursement-type`    VARCHAR(128) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_reimbursements_scope (account_id, seller_id, store_id, `approval-date`),
    INDEX idx_fba_reimbursements_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA reimbursements formal report raw rows';
