-- Formal Amazon FBA storage fee charges report evidence.
CREATE TABLE IF NOT EXISTS ls_fba_storage_fee_charges (
    account_id                         VARCHAR(32)  NOT NULL,
    seller_id                          VARCHAR(64)  NOT NULL,
    store_id                           VARCHAR(64)  NOT NULL DEFAULT '',
    report_task_id                     VARCHAR(128) NOT NULL,
    `row_number`                       INT UNSIGNED NOT NULL,
    row_sha256                         CHAR(64)     NOT NULL,
    asin                               VARCHAR(32)  NULL,
    fnsku                              VARCHAR(64)  NULL,
    product_name                       TEXT         NULL,
    fulfillment_center                 VARCHAR(64)  NULL,
    country_code                       VARCHAR(16)  NULL,
    longest_side                       VARCHAR(64)  NULL,
    median_side                        VARCHAR(64)  NULL,
    shortest_side                      VARCHAR(64)  NULL,
    measurement_units                  VARCHAR(32)  NULL,
    weight                             VARCHAR(64)  NULL,
    weight_units                       VARCHAR(32)  NULL,
    item_volume                        VARCHAR(64)  NULL,
    volume_units                       VARCHAR(32)  NULL,
    product_size_tier                  VARCHAR(128) NULL,
    average_quantity_on_hand           VARCHAR(64)  NULL,
    average_quantity_pending_removal   VARCHAR(64)  NULL,
    estimated_total_item_volume        VARCHAR(64)  NULL,
    month_of_charge                    VARCHAR(40)  NULL,
    storage_rate                       VARCHAR(64)  NULL,
    currency                           VARCHAR(16)  NULL,
    estimated_monthly_storage_fee      VARCHAR(64)  NULL,
    dangerous_goods_storage_type       VARCHAR(128) NULL,
    eligible_for_inventory_discount    VARCHAR(32)  NULL,
    qualifies_for_inventory_discount   VARCHAR(32)  NULL,
    total_incentive_fee_amount         VARCHAR(64)  NULL,
    breakdown_incentive_fee_amount     VARCHAR(64)  NULL,
    average_quantity_customer_orders   VARCHAR(64)  NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_storage_fee_scope (account_id, seller_id, store_id, month_of_charge),
    INDEX idx_fba_storage_fee_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA storage fee charges formal report raw rows';
