CREATE TABLE IF NOT EXISTS ls_fba_stranded_inventory (
    account_id VARCHAR(32) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL DEFAULT '',
    report_task_id VARCHAR(128) NOT NULL,
    `row_number` INT UNSIGNED NOT NULL,
    row_sha256 CHAR(64) NOT NULL,
    `primary-action` VARCHAR(128) NULL,
    `date-stranded` VARCHAR(40) NULL,
    `Date-to-take-auto-removal` VARCHAR(40) NULL,
    `status-primary` VARCHAR(64) NULL,
    `status-secondary` VARCHAR(128) NULL,
    `error-message` TEXT NULL,
    `stranded-reason` VARCHAR(256) NULL,
    asin VARCHAR(32) NULL,
    sku VARCHAR(128) NULL,
    fnsku VARCHAR(64) NULL,
    `product-name` TEXT NULL,
    `condition` VARCHAR(64) NULL,
    `fulfilled-by` VARCHAR(32) NULL,
    `fulfillable-qty` VARCHAR(64) NULL,
    `your-price` VARCHAR(64) NULL,
    `unfulfillable-qty` VARCHAR(64) NULL,
    `reserved-quantity` VARCHAR(64) NULL,
    `inbound-shipped-qty` VARCHAR(64) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_stranded_scope (account_id, seller_id, store_id, `date-stranded`),
    INDEX idx_fba_stranded_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA stranded inventory formal report raw rows';
