CREATE TABLE IF NOT EXISTS ls_fba_estimated_fees (
    account_id VARCHAR(32) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL DEFAULT '',
    report_task_id VARCHAR(128) NOT NULL,
    `row_number` INT UNSIGNED NOT NULL,
    row_sha256 CHAR(64) NOT NULL,
    sku VARCHAR(128) NULL,
    fnsku VARCHAR(64) NULL,
    asin VARCHAR(32) NULL,
    `product-name` TEXT NULL,
    `product-group` VARCHAR(128) NULL,
    brand VARCHAR(128) NULL,
    `fulfilled-by` VARCHAR(32) NULL,
    `has-local-inventory` VARCHAR(32) NULL,
    `your-price` VARCHAR(64) NULL,
    `sales-price` VARCHAR(64) NULL,
    `longest-side` VARCHAR(64) NULL,
    `median-side` VARCHAR(64) NULL,
    `shortest-side` VARCHAR(64) NULL,
    `length-and-girth` VARCHAR(64) NULL,
    `unit-of-dimension` VARCHAR(32) NULL,
    `item-package-weight` VARCHAR(64) NULL,
    `unit-of-weight` VARCHAR(32) NULL,
    `product-size-weight-band` VARCHAR(128) NULL,
    currency VARCHAR(16) NULL,
    `estimated-fee-total` VARCHAR(64) NULL,
    `estimated-referral-fee-per-unit` VARCHAR(64) NULL,
    `estimated-variable-closing-fee` VARCHAR(64) NULL,
    `expected-domestic-fulfilment-fee-per-unit` VARCHAR(64) NULL,
    `expected-efn-fulfilment-fee-per-unit-uk` VARCHAR(64) NULL,
    `expected-efn-fulfilment-fee-per-unit-de` VARCHAR(64) NULL,
    `expected-efn-fulfilment-fee-per-unit-fr` VARCHAR(64) NULL,
    `expected-efn-fulfilment-fee-per-unit-it` VARCHAR(64) NULL,
    `expected-efn-fulfilment-fee-per-unit-es` VARCHAR(64) NULL,
    `expected-efn-fulfilment-fee-per-unit-se` VARCHAR(64) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_estimated_fees_scope (account_id, seller_id, store_id, asin),
    INDEX idx_fba_estimated_fees_sku (account_id, seller_id, store_id, sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA estimated fees formal report raw rows';
