CREATE TABLE IF NOT EXISTS ls_fba_inbound_noncompliance (
    account_id VARCHAR(32) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL DEFAULT '',
    report_task_id VARCHAR(128) NOT NULL,
    `row_number` INT UNSIGNED NOT NULL,
    row_sha256 CHAR(64) NOT NULL,
    `issue-reported-date` VARCHAR(40) NULL,
    `shipment-creation-date` VARCHAR(40) NULL,
    `fba-shipment-id` VARCHAR(128) NULL,
    `fba-carton-id` VARCHAR(128) NULL,
    `fulfillment-center-id` VARCHAR(64) NULL,
    sku VARCHAR(128) NULL,
    fnsku VARCHAR(64) NULL,
    asin VARCHAR(32) NULL,
    `product-name` TEXT NULL,
    `problem-type` VARCHAR(128) NULL,
    `problem-quantity` VARCHAR(64) NULL,
    `expected-quantity` VARCHAR(64) NULL,
    `received-quantity` VARCHAR(64) NULL,
    `performance-measurement-unit` VARCHAR(64) NULL,
    `coaching-level` VARCHAR(64) NULL,
    `fee-type` VARCHAR(64) NULL,
    currency VARCHAR(16) NULL,
    `fee-total` VARCHAR(64) NULL,
    `problem-level` VARCHAR(64) NULL,
    `alert-status` VARCHAR(64) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_inbound_noncompliance_scope (account_id, seller_id, store_id, `issue-reported-date`),
    INDEX idx_fba_inbound_noncompliance_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA inbound noncompliance formal report raw rows';
