CREATE TABLE IF NOT EXISTS ls_fba_recommended_removals (
    account_id VARCHAR(32) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL DEFAULT '',
    report_task_id VARCHAR(128) NOT NULL,
    `row_number` INT UNSIGNED NOT NULL,
    row_sha256 CHAR(64) NOT NULL,
    `snapshot-date` VARCHAR(40) NULL,
    sku VARCHAR(128) NULL,
    fnsku VARCHAR(64) NULL,
    asin VARCHAR(32) NULL,
    `product-name` TEXT NULL,
    `condition` VARCHAR(64) NULL,
    `sellable-quantity` VARCHAR(64) NULL,
    `sellable-271-365-days` VARCHAR(64) NULL,
    `sellable-365+-days` VARCHAR(64) NULL,
    `sellable-removal-quantity` VARCHAR(64) NULL,
    `unsellable-quantity` VARCHAR(64) NULL,
    `unsellable-0-7-days` VARCHAR(64) NULL,
    `unsellable-8-60-days` VARCHAR(64) NULL,
    `unsellable-61-90-days` VARCHAR(64) NULL,
    `sellable-121-180-days` VARCHAR(64) NULL,
    `sellable-181-270-days` VARCHAR(64) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_recommended_removal_scope (account_id, seller_id, store_id, `snapshot-date`),
    INDEX idx_fba_recommended_removal_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA recommended removal formal report raw rows';
