CREATE TABLE IF NOT EXISTS ls_amazon_all_orders_by_order_date (
    account_id VARCHAR(32) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL DEFAULT '',
    report_task_id VARCHAR(128) NOT NULL,
    `row_number` INT UNSIGNED NOT NULL,
    row_sha256 CHAR(64) NOT NULL,
    `amazon-order-id` VARCHAR(128) NULL,
    `merchant-order-id` VARCHAR(128) NULL,
    `purchase-date` VARCHAR(40) NULL,
    `last-updated-date` VARCHAR(40) NULL,
    `order-status` VARCHAR(64) NULL,
    `fulfillment-channel` VARCHAR(64) NULL,
    `sales-channel` VARCHAR(128) NULL,
    `order-channel` VARCHAR(128) NULL,
    `ship-service-level` VARCHAR(128) NULL,
    `product-name` TEXT NULL,
    sku VARCHAR(128) NULL,
    asin VARCHAR(32) NULL,
    `item-status` VARCHAR(64) NULL,
    quantity VARCHAR(64) NULL,
    currency VARCHAR(16) NULL,
    `item-price` VARCHAR(64) NULL,
    `item-tax` VARCHAR(64) NULL,
    `shipping-price` VARCHAR(64) NULL,
    `shipping-tax` VARCHAR(64) NULL,
    `gift-wrap-price` VARCHAR(64) NULL,
    `gift-wrap-tax` VARCHAR(64) NULL,
    `item-promotion-discount` VARCHAR(64) NULL,
    `ship-promotion-discount` VARCHAR(64) NULL,
    `ship-city` VARCHAR(128) NULL,
    `ship-state` VARCHAR(128) NULL,
    `ship-postal-code` VARCHAR(64) NULL,
    `ship-country` VARCHAR(64) NULL,
    `promotion-ids` TEXT NULL,
    `is-business-order` VARCHAR(16) NULL,
    `purchase-order-number` VARCHAR(128) NULL,
    `price-designation` VARCHAR(64) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_amazon_all_orders_scope (account_id, seller_id, store_id, `purchase-date`),
    INDEX idx_amazon_all_orders_asin (account_id, seller_id, store_id, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon all orders by order date formal report raw rows';
