CREATE TABLE IF NOT EXISTS ls_amazon_fulfilled_shipments (
    account_id                    VARCHAR(32)  NOT NULL,
    seller_id                     VARCHAR(64)  NOT NULL,
    store_id                      VARCHAR(64)  NOT NULL DEFAULT '',
    report_task_id                VARCHAR(128) NOT NULL,
    `row_number`                  INT UNSIGNED NOT NULL,
    row_sha256                    CHAR(64)     NOT NULL,
    `amazon-order-id`             VARCHAR(128) NULL,
    `merchant-order-id`           VARCHAR(128) NULL,
    `shipment-id`                 VARCHAR(128) NULL,
    `shipment-item-id`            VARCHAR(128) NULL,
    `amazon-order-item-id`        VARCHAR(128) NULL,
    `merchant-order-item-id`      VARCHAR(128) NULL,
    `purchase-date`               VARCHAR(40)  NULL,
    `payments-date`               VARCHAR(40)  NULL,
    `shipment-date`               VARCHAR(40)  NULL,
    `reporting-date`              VARCHAR(40)  NULL,
    `buyer-email`                 VARCHAR(320) NULL,
    `buyer-name`                  TEXT         NULL,
    `buyer-phone-number`          VARCHAR(64)  NULL,
    sku                            VARCHAR(256) NULL,
    `product-name`                TEXT         NULL,
    `quantity-shipped`            VARCHAR(32)  NULL,
    currency                       VARCHAR(16)  NULL,
    `item-price`                  VARCHAR(64)  NULL,
    `item-tax`                    VARCHAR(64)  NULL,
    `shipping-price`              VARCHAR(64)  NULL,
    `shipping-tax`                VARCHAR(64)  NULL,
    `gift-wrap-price`             VARCHAR(64)  NULL,
    `gift-wrap-tax`               VARCHAR(64)  NULL,
    `ship-service-level`          VARCHAR(128) NULL,
    `recipient-name`              TEXT         NULL,
    `ship-address-1`              TEXT         NULL,
    `ship-address-2`              TEXT         NULL,
    `ship-address-3`              TEXT         NULL,
    `ship-city`                   VARCHAR(256) NULL,
    `ship-state`                  VARCHAR(256) NULL,
    `ship-postal-code`            VARCHAR(64)  NULL,
    `ship-country`                VARCHAR(16)  NULL,
    `ship-phone-number`           VARCHAR(64)  NULL,
    `bill-address-1`              TEXT         NULL,
    `bill-address-2`              TEXT         NULL,
    `bill-address-3`              TEXT         NULL,
    `bill-city`                   VARCHAR(256) NULL,
    `bill-state`                  VARCHAR(256) NULL,
    `bill-postal-code`            VARCHAR(64)  NULL,
    `bill-country`                VARCHAR(16)  NULL,
    `item-promotion-discount`     VARCHAR(64)  NULL,
    `ship-promotion-discount`     VARCHAR(64)  NULL,
    carrier                        VARCHAR(128) NULL,
    `tracking-number`             VARCHAR(256) NULL,
    `estimated-arrival-date`      VARCHAR(40)  NULL,
    `fulfillment-center-id`       VARCHAR(64)  NULL,
    `fulfillment-channel`         VARCHAR(64)  NULL,
    `sales-channel`               VARCHAR(128) NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_amazon_fulfilled_scope (account_id, seller_id, store_id, `shipment-date`),
    INDEX idx_amazon_fulfilled_order (account_id, seller_id, store_id, `amazon-order-id`),
    INDEX idx_amazon_fulfilled_shipment (account_id, seller_id, store_id, `shipment-id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA fulfilled shipments formal report raw rows including PII';
