-- FBA inventory raw data is current-state. Preserve each successful daily
-- response as a dated, system-owned snapshot without changing the raw table.
CREATE TABLE IF NOT EXISTS fba_inventory_daily_snapshots (
    account_id VARCHAR(32) NOT NULL,
    snapshot_date DATE NOT NULL,
    afn_erp_real_shipped_quantity INT NULL,
    afn_fulfillable_quantity INT NULL,
    afn_fulfillable_quantity_multi JSON NULL,
    afn_inbound_receiving_quantity INT NULL,
    afn_inbound_shipped_quantity INT NULL,
    afn_inbound_working_quantity INT NULL,
    afn_researching_quantity INT NULL,
    afn_reserved_quantity INT NULL,
    afn_unsellable_quantity INT NULL,
    asin VARCHAR(16) NULL,
    brand_id BIGINT NULL,
    brand_name VARCHAR(128) NULL,
    category_id BIGINT NULL,
    category_name VARCHAR(128) NULL,
    cost DECIMAL(14,4) NULL,
    estimated_excess_quantity DECIMAL(14,4) NULL,
    estimated_storage_cost_next_month DECIMAL(14,4) NULL,
    fba_inventory_level_health_status VARCHAR(64) NULL,
    fba_minimum_inventory_level DECIMAL(14,4) NULL,
    fnsku VARCHAR(32) NOT NULL,
    fulfillment_channel_name VARCHAR(32) NULL,
    historical_days_of_supply DECIMAL(14,4) NULL,
    inv_age_0_to_30_days INT NULL,
    inv_age_0_to_90_days INT NULL,
    inv_age_181_to_270_days INT NULL,
    inv_age_271_to_330_days INT NULL,
    inv_age_271_to_365_days INT NULL,
    inv_age_31_to_60_days INT NULL,
    inv_age_331_to_365_days INT NULL,
    inv_age_365_plus_days INT NULL,
    inv_age_61_to_90_days INT NULL,
    inv_age_91_to_180_days INT NULL,
    long_term_historical_days_of_supply DECIMAL(14,4) NULL,
    low_inventory_level_fee_applied VARCHAR(32) NULL,
    msku VARCHAR(128) NULL,
    name VARCHAR(256) NULL,
    product_image VARCHAR(512) NULL,
    product_name VARCHAR(256) NULL,
    recommended_action VARCHAR(64) NULL,
    reserved_customerorders INT NULL,
    reserved_fc_processing INT NULL,
    reserved_fc_transfers INT NULL,
    sell_through DECIMAL(10,4) NULL,
    share_type VARCHAR(32) NULL,
    short_term_historical_days_of_supply DECIMAL(14,4) NULL,
    sid VARCHAR(32) NOT NULL,
    sku VARCHAR(128) NULL,
    stock_cost_total DECIMAL(14,4) NULL,
    total_fulfillable_quantity INT NULL,
    wname VARCHAR(64) NULL,
    source_synced_at DATETIME NOT NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (account_id, sid, fnsku, snapshot_date),
    INDEX idx_fba_inventory_snapshot_date (sid, snapshot_date, account_id),
    INDEX idx_fba_inventory_snapshot_asin (account_id, sid, asin, snapshot_date),
    INDEX idx_fba_inventory_snapshot_sku (account_id, sid, sku, snapshot_date),
    INDEX idx_fba_inventory_snapshot_changes (sid, updated_at, account_id, fnsku, snapshot_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
