CREATE TABLE IF NOT EXISTS ls_fba_inventory_planning (
    account_id VARCHAR(32) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL DEFAULT '',
    report_task_id VARCHAR(128) NOT NULL,
    `row_number` INT UNSIGNED NOT NULL,
    row_sha256 CHAR(64) NOT NULL,
    `snapshot-date` TEXT NULL,
    `sku` TEXT NULL,
    `fnsku` TEXT NULL,
    `asin` TEXT NULL,
    `product-name` TEXT NULL,
    `condition` TEXT NULL,
    `available` TEXT NULL,
    `fc-transfer` TEXT NULL,
    `pending-removal-quantity` TEXT NULL,
    `inv-age-0-to-90-days` TEXT NULL,
    `inv-age-91-to-180-days` TEXT NULL,
    `inv-age-181-to-270-days` TEXT NULL,
    `inv-age-271-to-365-days` TEXT NULL,
    `inv-age-366-to-455-days` TEXT NULL,
    `inv-age-456-plus-days` TEXT NULL,
    `currency` TEXT NULL,
    `units-shipped-t7` TEXT NULL,
    `units-shipped-t30` TEXT NULL,
    `units-shipped-t60` TEXT NULL,
    `units-shipped-t90` TEXT NULL,
    `alert` TEXT NULL,
    `your-price` TEXT NULL,
    `sales-price` TEXT NULL,
    `lowest-price-new-plus-shipping` TEXT NULL,
    `lowest-price-used` TEXT NULL,
    `recommended-action` TEXT NULL,
    `DEPRECATED healthy-inventory-level` TEXT NULL,
    `recommended-sales-price` TEXT NULL,
    `recommended-sale-duration-days` TEXT NULL,
    `recommended-removal-quantity` TEXT NULL,
    `estimated-cost-savings-of-recommended-actions` TEXT NULL,
    `sell-through` TEXT NULL,
    `item-volume` TEXT NULL,
    `volume-unit-measurement` TEXT NULL,
    `storage-type` TEXT NULL,
    `storage-volume` TEXT NULL,
    `marketplace` TEXT NULL,
    `product-group` TEXT NULL,
    `sales-rank` TEXT NULL,
    `days-of-supply` TEXT NULL,
    `estimated-excess-quantity` TEXT NULL,
    `weeks-of-cover-t30` TEXT NULL,
    `weeks-of-cover-t90` TEXT NULL,
    `featuredoffer-price` TEXT NULL,
    `sales-shipped-last-7-days` TEXT NULL,
    `sales-shipped-last-30-days` TEXT NULL,
    `sales-shipped-last-60-days` TEXT NULL,
    `sales-shipped-last-90-days` TEXT NULL,
    `inv-age-0-to-30-days` TEXT NULL,
    `inv-age-31-to-60-days` TEXT NULL,
    `inv-age-61-to-90-days` TEXT NULL,
    `inv-age-181-to-330-days` TEXT NULL,
    `inv-age-331-to-365-days` TEXT NULL,
    `estimated-storage-cost-next-month` TEXT NULL,
    `inbound-quantity` TEXT NULL,
    `inbound-working` TEXT NULL,
    `inbound-shipped` TEXT NULL,
    `inbound-received` TEXT NULL,
    `no-sale-last-6-months` TEXT NULL,
    `Total Reserved Quantity` TEXT NULL,
    `unfulfillable-quantity` TEXT NULL,
    `quantity-to-be-charged-ais-181-210-days` TEXT NULL,
    `estimated-ais-181-210-days` TEXT NULL,
    `quantity-to-be-charged-ais-211-240-days` TEXT NULL,
    `estimated-ais-211-240-days` TEXT NULL,
    `quantity-to-be-charged-ais-241-270-days` TEXT NULL,
    `estimated-ais-241-270-days` TEXT NULL,
    `quantity-to-be-charged-ais-271-300-days` TEXT NULL,
    `estimated-ais-271-300-days` TEXT NULL,
    `quantity-to-be-charged-ais-301-330-days` TEXT NULL,
    `estimated-ais-301-330-days` TEXT NULL,
    `quantity-to-be-charged-ais-331-365-days` TEXT NULL,
    `estimated-ais-331-365-days` TEXT NULL,
    `quantity-to-be-charged-ais-366-455-days` TEXT NULL,
    `estimated-ais-366-455-days` TEXT NULL,
    `quantity-to-be-charged-ais-456-plus-days` TEXT NULL,
    `estimated-ais-456-plus-days` TEXT NULL,
    `historical-days-of-supply` TEXT NULL,
    `fba-minimum-inventory-level` TEXT NULL,
    `fba-inventory-level-health-status` TEXT NULL,
    `Recommended ship-in quantity` TEXT NULL,
    `Recommended ship-in date` TEXT NULL,
    `Last updated date for Historical Days of Supply` TEXT NULL,
    `Exempted from Low-Inventory-Level fee?` TEXT NULL,
    `Low-Inventory-Level fee applied in current week?` TEXT NULL,
    `Short term historical days of supply` TEXT NULL,
    `Long term historical days of supply` TEXT NULL,
    `Inventory age snapshot date` TEXT NULL,
    `Inventory Supply at FBA` TEXT NULL,
    `Reserved FC Processing` TEXT NULL,
    `Reserved Customer Order` TEXT NULL,
    `Reserved Staging` TEXT NULL,
    `Total Days of Supply (including units from open shipments)` TEXT NULL,
    `supplier` TEXT NULL,
    `is-seasonal-in-next-3-months` TEXT NULL,
    `season-name` TEXT NULL,
    `season-start-date` TEXT NULL,
    `season-end-date` TEXT NULL,
    `Fulfillment Service and Programs` TEXT NULL,
    PRIMARY KEY (report_task_id, `row_number`),
    INDEX idx_fba_inventory_planning_asin (account_id, seller_id, store_id, `asin`(32)),
    INDEX idx_fba_inventory_planning_sku (account_id, seller_id, store_id, `sku`(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Amazon FBA Inventory Planning formal report raw rows';
