-- /erp/sc/data/mws/orderDetail 的原始响应。一个账号、店铺、亚马逊订单一行，
-- item_list 保留上游商品数组，不在原始表拆分或加工。
CREATE TABLE IF NOT EXISTS ls_sc_order_details (
    account_id                       VARCHAR(32) NOT NULL COMMENT '本系统内部账号 ID（非领星字段）',
    sid                              VARCHAR(32) NOT NULL COMMENT '领星店铺 ID',
    amazon_order_id                  VARCHAR(64) NOT NULL COMMENT '亚马逊订单号',
    fulfillment_channel              VARCHAR(16) NULL,
    order_status                     VARCHAR(32) NULL,
    order_total_amount               VARCHAR(32) NULL,
    currency                         VARCHAR(8) NULL,
    icon                             VARCHAR(16) NULL,
    is_assessed                      TINYINT NULL,
    is_mcf_order                     TINYINT NULL,
    is_return_order                  TINYINT NULL,
    is_replaced_order                TINYINT NULL,
    is_replacement_order             TINYINT NULL,
    purchase_date_local              VARCHAR(32) NULL,
    purchase_date_local_utc          VARCHAR(32) NULL,
    last_update_date                 VARCHAR(32) NULL,
    last_update_date_utc             VARCHAR(32) NULL,
    posted_date                      VARCHAR(32) NULL,
    shipment_date                    VARCHAR(32) NULL,
    earliest_ship_date               VARCHAR(32) NULL,
    earliest_ship_date_utc           VARCHAR(32) NULL,
    is_business_order                TINYINT NULL,
    is_prime                         TINYINT NULL,
    is_premium_order                 TINYINT NULL,
    is_promotion                     TINYINT NULL,
    taxes_included                   TINYINT NULL,
    ship_service_level               VARCHAR(64) NULL,
    shipment_service_level_category  VARCHAR(64) NULL,
    purchase_order_number            VARCHAR(64) NULL,
    payment_method                   VARCHAR(64) NULL,
    cba_displayable_shipping_label   VARCHAR(255) NULL,
    order_type                       VARCHAR(64) NULL,
    latest_ship_date                 VARCHAR(32) NULL,
    earliest_delivery_date           VARCHAR(32) NULL,
    latest_delivery_date             VARCHAR(32) NULL,
    number_of_items_shipped          BIGINT NULL,
    number_of_items_unshipped        BIGINT NULL,
    sales_channel                    VARCHAR(128) NULL,
    item_list                        JSON NULL COMMENT '上游订单商品数组，字段保持原样',
    synced_at                        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (account_id, sid, amazon_order_id),
    KEY idx_order_detail_order (account_id, amazon_order_id),
    KEY idx_order_detail_updated (account_id, last_update_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
