-- /pb/mp/order/v2/list 的 FBM/多平台订单原始响应。
-- 一行一个上游订单；item_info/address_info/platform_info 保留原始 JSON，
-- 商品行由独立数据集 Reader 按 global_item_no 展开。
CREATE TABLE IF NOT EXISTS ls_mp_fbm_orders (
    account_id                 VARCHAR(32) NOT NULL,
    store_id                   VARCHAR(64) NOT NULL,
    global_order_no            VARCHAR(128) NOT NULL,
    original_global_order_no   VARCHAR(128) NULL,
    reference_no               VARCHAR(128) NULL,
    wid                        VARCHAR(64) NULL,
    store_name                 VARCHAR(255) NULL,
    warehouse_name             VARCHAR(255) NULL,
    supplier_id                VARCHAR(64) NULL,
    amount_currency            VARCHAR(16) NULL,
    order_from_name            VARCHAR(128) NULL,
    remark                     VARCHAR(1024) NULL,
    status                     INT NULL,
    flow_node                  INT NULL,
    status_sub                 INT NULL,
    delivery_type              INT NULL,
    split_type                 VARCHAR(64) NULL,
    is_delete                  TINYINT NULL,
    global_create_time         VARCHAR(40) NULL,
    update_time                VARCHAR(40) NULL,
    global_purchase_time       BIGINT NULL,
    global_payment_time        BIGINT NULL,
    global_delivery_time       BIGINT NULL,
    global_distribution_time   BIGINT NULL,
    global_latest_ship_time    VARCHAR(40) NULL,
    global_review_time         BIGINT NULL,
    global_cancel_time         BIGINT NULL,
    global_print_time          BIGINT NULL,
    global_mark_time           BIGINT NULL,
    address_info               JSON NULL,
    buyers_info                JSON NULL,
    customer_shipping_list     JSON NULL,
    item_info                  JSON NULL,
    logistics_info             JSON NULL,
    order_custom_fields        JSON NULL,
    order_tag                  JSON NULL,
    exception_order_tag        JSON NULL,
    pending_order_tag          JSON NULL,
    payment_info               JSON NULL,
    platform_info              JSON NULL,
    transaction_info           JSON NULL,
    vc_ship_method              VARCHAR(128) NULL,
    vc_warehouse_code           VARCHAR(64) NULL,
    sender_tax_no              VARCHAR(128) NULL,
    sender_tax_type            VARCHAR(64) NULL,
    synced_at                  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (account_id, store_id, global_order_no),
    KEY idx_mp_fbm_order_updated (account_id, update_time),
    KEY idx_mp_fbm_purchase (account_id, global_purchase_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='领星 MultiPlat FBM 订单原始事实';
